<div class='container m-5 col'>
    <form action="/index/addWord" method="post">
        <label for="english"></label>
        English : <input type="text" name="english" class = 'form form-control col-3'>

        <label for="dutch"></label>
        Dutch :<input type="text" name="dutch" class = 'form form-control col-3'>

        <input type="submit" value = 'Add Word' class = 'btn btn-success my-3'>
    </form>
    <a href="/index/dictToFile" class = 'btn btn-primary'>Show All words</a>
</div>
